services:
  - type: web
    name: operaiq
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./apps/web/Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://operaiq-api.3.208.71.125.sslip.io
      - key: NEXT_PUBLIC_QDRANT_DASHBOARD_URL
        value: ""
